services:
  redis:
    image: redis:latest
    container_name: redis
    platform: linux/amd64
    ports:
      - "6379:6379"
    restart: always

  fastapi-app:
    build:
      context: ./fastapi_app
      dockerfile: Dockerfile_fastapi
      platforms:
        - linux/amd64
    image: capstoneprojectaiml.azurecr.io/fastapi-app:latest
    container_name: fastapi-app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis

  streamlit-app:
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile_streamlit
      platforms:
        - linux/amd64
    image: capstoneprojectaiml.azurecr.io/streamlit-app:latest
    container_name: streamlit-app
    command: streamlit run streamlit.py --server.port=8501
    ports:
      - "8501:8501"
    depends_on:
      - fastapi-app
